### ISSUE TITLE
你好这是什么原因

### ISSUE THREAD

**Issue by mars918** [Xuxiangqi123456/keras_garbage_classify#1]
2020-03-13 10:05:43.700663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2020-03-13 10:05:43.702378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3019 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
Epoch 1/20
Using TensorFlow backend.
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:/Users/Administrator/OneDrive/桌面/garbage_classify-master/garbage_train.py", line 283, in <module>
    shuffle=True
  File "D:\Anaconda\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "D:\Anaconda\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "D:\Anaconda\lib\site-packages\keras\engine\training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "D:\Anaconda\lib\site-packages\keras\engine\training.py", line 1211, in train_on_batch
    class_weight=class_weight)
  File "D:\Anaconda\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "D:\Anaconda\lib\site-packages\keras\engine\training_utils.py", line 128, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (16, 1)

**Comment by Xuxiangqi123456** [comment]
输入图像维度问题


 
---原始邮件---
发件人: "mars"<notifications@github.com&gt;
发送时间: 2020年3月13日(星期五) 上午10:10
收件人: "Xuxiangqi123456/keras_garbage_classify"<keras_garbage_classify@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Xuxiangqi123456/keras_garbage_classify] 你好这是什么原因 (#1)




 
2020-03-13 10:05:43.700663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
 2020-03-13 10:05:43.702378: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3019 MB memory) -&gt; physical GPU (device: 0, name: GeForce GTX 1050, pci bus id: 0000:01:00.0, compute capability: 6.1)
 Epoch 1/20
 Using TensorFlow backend.
 Using TensorFlow backend.
 Traceback (most recent call last):
 File "C:/Users/Administrator/OneDrive/桌面/garbage_classify-master/garbage_train.py", line 283, in 
 shuffle=True
 File "D:\Anaconda\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
 return func(*args, **kwargs)
 File "D:\Anaconda\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
 initial_epoch=initial_epoch)
 File "D:\Anaconda\lib\site-packages\keras\engine\training_generator.py", line 217, in fit_generator
 class_weight=class_weight)
 File "D:\Anaconda\lib\site-packages\keras\engine\training.py", line 1211, in train_on_batch
 class_weight=class_weight)
 File "D:\Anaconda\lib\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
 exception_prefix='input')
 File "D:\Anaconda\lib\site-packages\keras\engine\training_utils.py", line 128, in standardize_input_data
 'with shape ' + str(data_shape))
 ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (16, 1)
